server:
  port: 9106
spring:
  application:
    name: linkis-ps-datasource


eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:20303/eureka/
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
  health:
    db:
      enabled: false
logging:
  config: classpath:log4j2.xml