server:
  port: 9116
spring:
  application:
    name: prestoEntrance


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20303/eureka/
  instance:
    metadata-map:
      test: enjoyyin

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml
#    register-with-eureka: false
#    fetch-registry: false