server:
  port: 9104
spring:
  application:
    name: linkis-cg-entrance


eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:20303/eureka/
  instance:
    metadata-map:
      test:

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml
#    register-with-eureka: false
#    fetch-registry: false
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000